DROP TABLE cuentaconsumos CASCADE CONSTRAINTS;

DROP TABLE establecimientos CASCADE CONSTRAINTS;

DROP TABLE gimnasios CASCADE CONSTRAINTS;

DROP TABLE habitaciones CASCADE CONSTRAINTS;

DROP TABLE internet CASCADE CONSTRAINTS;

DROP TABLE lavanderias CASCADE CONSTRAINTS;

DROP TABLE ofrecenproductos CASCADE CONSTRAINTS;

DROP TABLE piscinas CASCADE CONSTRAINTS;

DROP TABLE planesconsumo CASCADE CONSTRAINTS;

DROP TABLE prestamos CASCADE CONSTRAINTS;

DROP TABLE productos CASCADE CONSTRAINTS;

DROP TABLE reservasalojamiento CASCADE CONSTRAINTS;

DROP TABLE reservasservicio CASCADE CONSTRAINTS;

DROP TABLE salones CASCADE CONSTRAINTS;

DROP TABLE servicios CASCADE CONSTRAINTS;

DROP TABLE spas CASCADE CONSTRAINTS;

DROP TABLE tiposhabitacion CASCADE CONSTRAINTS;

DROP TABLE tiposusuario CASCADE CONSTRAINTS;

DROP TABLE usuarios CASCADE CONSTRAINTS;