DROP SEQUENCE hotelandes_sequence;

DROP TABLE consumos CASCADE CONSTRAINTS;

DROP TABLE habitaciones CASCADE CONSTRAINTS;

DROP TABLE ofrecenproductos CASCADE CONSTRAINTS;

DROP TABLE planesconsumo CASCADE CONSTRAINTS;

DROP TABLE productos CASCADE CONSTRAINTS;

DROP TABLE reservasalojamiento CASCADE CONSTRAINTS;

DROP TABLE reservasservicio CASCADE CONSTRAINTS;

DROP TABLE servicios CASCADE CONSTRAINTS;

DROP TABLE tiposhabitacion CASCADE CONSTRAINTS;

DROP TABLE tiposusuario CASCADE CONSTRAINTS;

DROP TABLE usuarios CASCADE CONSTRAINTS;